[default]
DEBUG = false
FLASK_ADMIN_SWATCH = "cerulean"
ADMIN_NAME = "Gilberto (dev mode)"
EXTENSIONS = [
    "ext.site:init_app"
]

[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = "sqlite:///internals.db"
SQLALCHEMY_TRACK_MODIFICATIONS = false
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = true
DEBUG_TB_PROFILER_ENABLED = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
ADMIN_NAME = "Gilberto (dev mode)"
EXTENSIONS = [
    "ext.site:init_app"
]


[production]
SQLALCHEMY_TRACK_MODIFICATIONS = false
SQLALCHEMY_DATABASE_URI = "mysql://...."